default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: titan_development
  username: titan
  host: localhost

test: &test
  <<: *default
  database: titan_development
  username: titan
  host: localhost

production:
  <<: *default
  database: OneCallNowRails_test
  username: OneCallNow
