default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: titan_development
  username: titan
  password: abcd1234
  host: localhost

test: &test
  <<: *default
  database: titan_development
  username: titan
  password: <%= ENV["DB_PASSWORD"] %>
  host: localhost

production:
  <<: *default
  database: titan_development
  username: titan
  password: <%= ENV["DB_PASSWORD"] %>
  host: localhost
